#!/bin/sh
 
# Run the test suite.
# It will exit with 0 if it everything compiled and tested fine.
echo "Testing project before commit..."
cd annotation-bundle
mvn clean test
if [ $? -eq 0 ]; then
  echo "Run sonar? (default is no)? (y/n):"
  read sonar
  if [ "$sonar" == "y" ]; then
    mvn sonar:sonar
    echo "Proceed with commit (default is no)? (y/n):"
    read commit
    if [ "$commit" != "y" ]; then
      echo ""
      echo "commit aborted"
      exit 1
    fi
  fi
  exit 0
else
  echo ""
  echo "Building your project or running the tests failed."
  echo "Aborting the commit. Run with --no-verify to ignore."
  exit 1
fi
